# Generated by Django 4.0.6 on 2022-08-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_pics/divzy.png', upload_to='profile_pics'),
        ),
    ]
